### ISSUE TITLE
Some question about CrackMe,SharifCTF8

### ISSUE THREAD

**Issue by Rayjoke** [VoidHack/write-ups#2]
I can not pass verification using CZKY^G in SharifCTF8--CrackMe. My friend pass verification using CZJYJG in his windows(64 bit, virtual machine), but I can not pass in my x64 windows(not vm)... The other problem is that this program use RDTSC, making my submit incorrectly at next time(in OLLYDBG). Such a confusing program it is...  Can you tell me why? THANKS.

**Comment by konatabrk** [comment]
Sorry, there was a little misunderstanding. Wait a few moments, I will change write-up in the right way

**Comment by konatabrk** [comment]
Now you can write it again. Thank you for your help! :3
